server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  max_block_duration: 5m
  max_block_bytes: 50_000_000

compactor:
  compaction:
    block_retention: 24h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

metrics_generator:
  storage:
    path: /var/tempo/generator/wal
  traces_storage:
    path: /tmp/tempo/generator/traces

overrides:
  defaults:
    metrics_generator:
      processors: [span-metrics, service-graphs, local-blocks]
